{% set version = "1.0.2" %}
{% set name = "patsy" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cdc995455f6233e90e22de72c37fcadb344e7586fb83f06696f54d92f8ce74c0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy >=1.4

test:
  source_files:
    - patsy
  imports:
    - patsy
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v patsy

about:
  home: https://github.com/pydata/patsy
  license: BSD-2-Clause AND PSF-2.0
  license_family: BSD
  license_file: LICENSE.txt
  summary: Describing statistical models in Python using symbolic formulas
  description: |
    Patsy is a Python library for describing statistical models (especially
    linear models, or models that have a linear component) and building design
    matrices.
  doc_url: https://patsy.readthedocs.io
  dev_url: https://github.com/pydata/patsy

extra:
  recipe-maintainers:
    - bollwyvl
    - croth1
