{% set version = "0.5.2" %}
{% set pkg_name = "patsy" %}


package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pkg_name[0] }}/{{ pkg_name }}/{{ pkg_name }}-{{ version }}.tar.gz
  sha256: 5053de7804676aba62783dbb0f23a2b3d74e35e5bfa238b88b7cbf148a38b69d

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # need at least numpy 1.4 for triu_indices
    - numpy >=1.4.0
    - six
    # Optional: scipy needed for spline-related functions like bs 
    - scipy

test:
  imports:
    - patsy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pydata/patsy
  license: BSD-2-Clause AND PSF-2.0
  license_family: BSD
  license_file: LICENSE.txt
  summary: Describing statistical models in Python using symbolic formulas
  description: |
    Patsy is a Python library for describing statistical models (especially
    linear models, or models that have a linear component) and building design
    matrices.
  doc_url: http://patsy.readthedocs.org/en/latest/
  doc_source_url: https://github.com/pydata/patsy/blob/master/doc/index.rst
  dev_url: https://github.com/pydata/patsy

extra:
  recipe-maintainers:
    - bollwyvl
    - croth1
