{% set version = "0.5.6" %}
{% set pkg_name = "patsy" %}


package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pkg_name[0] }}/{{ pkg_name }}/{{ pkg_name }}-{{ version }}.tar.gz
  sha256: 95c6d47a7222535f84bff7f63d7303f2e297747a598db89cf5c67f0c0c7d2cdb

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # need at least numpy 1.4 for triu_indices
    - numpy >=1.4.0
    - six

test:
  imports:
    - patsy
  requires:
    - pip
    # Optional: scipy needed for spline-related functions like bs 
    #- scipy
  commands:
    - pip check

about:
  home: https://github.com/pydata/patsy
  license: BSD-2-Clause AND PSF-2.0
  license_family: BSD
  license_file: LICENSE.txt
  summary: Describing statistical models in Python using symbolic formulas
  description: |
    Patsy is a Python library for describing statistical models (especially
    linear models, or models that have a linear component) and building design
    matrices.
  doc_url: https://patsy.readthedocs.io
  dev_url: https://github.com/pydata/patsy

extra:
  recipe-maintainers:
    - bollwyvl
    - croth1
