# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Rm6/FsHC4Fo1i3jkz6VA4QLoL+6kgtY1XdafSZSUfeLFIz0s7tBrjtOplAoE1SrVMk5+d9/DFjqa16/hCmMta2yz/ajSwYe7o41Jxja5cRNlYeybkcWUuYflrXiTBzKg97pRziVJtZdVMWoV4/9OR1oaEsfCEqIWGkOr/puZvuOypp39toPH+80vOiVvaAsP7p6ut7nF2gFcPtOmcWh9dWiiTR6DtBkFjHJf+DWtkZ94t6YHtwvq46TfBHnsSGbK+9Pl232Wmj7NAjzZGIlgEcAiFOtlv/ZmaIaNjCyubAJSUyydyEAv38hyzGJIxQL/P0FS28Ooex4lnKHpeeMd5Macj6tF8LbuieKZGa2rrWqP7bdB10rUdnHDpec+qcZdGqGgYmnO/A1VpGtUTvrFFCFL8luo3wcokdRl+mMk2zOwn5/luZqvgE2p9b97vW2dqzz/cSy5F56gnK5ulGdqQFAzIa8hmev5gxyo/msJU4/mkJ3JgF+2WWPjrrOxqJ8uY9O5/bhls4WMlynireqfnJUT+JgER5gCtjb317veGEnzNDiwLTSsTyJ7A3aKCMmwCQIccUhUGz4f1E9Noor8BsBJrh8RJKZfVpYPVWf27dTlOP0v0i0B/QYziG6AQD8NqiHeBQAzrBxCHZ5YC8NeSXErS9U2L4yIz0Nshkxn1MU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
