travis:
  secure:
    BINSTAR_TOKEN: Rm6/FsHC4Fo1i3jkz6VA4QLoL+6kgtY1XdafSZSUfeLFIz0s7tBrjtOplAoE1SrVMk5+d9/DFjqa16/hCmMta2yz/ajSwYe7o41Jxja5cRNlYeybkcWUuYflrXiTBzKg97pRziVJtZdVMWoV4/9OR1oaEsfCEqIWGkOr/puZvuOypp39toPH+80vOiVvaAsP7p6ut7nF2gFcPtOmcWh9dWiiTR6DtBkFjHJf+DWtkZ94t6YHtwvq46TfBHnsSGbK+9Pl232Wmj7NAjzZGIlgEcAiFOtlv/ZmaIaNjCyubAJSUyydyEAv38hyzGJIxQL/P0FS28Ooex4lnKHpeeMd5Macj6tF8LbuieKZGa2rrWqP7bdB10rUdnHDpec+qcZdGqGgYmnO/A1VpGtUTvrFFCFL8luo3wcokdRl+mMk2zOwn5/luZqvgE2p9b97vW2dqzz/cSy5F56gnK5ulGdqQFAzIa8hmev5gxyo/msJU4/mkJ3JgF+2WWPjrrOxqJ8uY9O5/bhls4WMlynireqfnJUT+JgER5gCtjb317veGEnzNDiwLTSsTyJ7A3aKCMmwCQIccUhUGz4f1E9Noor8BsBJrh8RJKZfVpYPVWf27dTlOP0v0i0B/QYziG6AQD8NqiHeBQAzrBxCHZ5YC8NeSXErS9U2L4yIz0Nshkxn1MU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
